# Generated by Django 3.1.5 on 2021-01-25 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('noc', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_athlete', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=50)),
                ('games', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('medal', models.CharField(max_length=10)),
                ('noc', models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='olimpic.noc', verbose_name='NOC')),
            ],
        ),
    ]
